### ISSUE TITLE
Readability of COG heatmaps

### ISSUE THREAD

**Issue by tpillone** [metagenlab/chlamdb#12]
COG heatmaps are currently difficult to read. It could be nice to color columns using a continuous scale (to see genomes with higher or lower counts). We could add the option to SimpleColorColumn?

![Screenshot from 2021-11-04 11-38-27(1)](https://user-images.githubusercontent.com/33416812/140300814-f6c0e37a-a052-4418-b899-0670ea784d86.png)

**Comment by bkm** [comment]
Yes, it is indeed in my to do list.

**Comment by bkm** [comment]
Fixed. You'll need to also update metagenlab_libs to the most recent version.
