### ISSUE TITLE
Error message when attempting to acces ChlamDB

### ISSUE THREAD

**Issue by Sam-Leistiko** [metagenlab/chlamdb#33]
Every time I try to access ChlamDB, I get an error message. I have attached a picture of this particular error below.
![Screenshot 2024-01-26 123020](https://github.com/metagenlab/chlamdb/assets/120612984/28bee6b9-1987-4417-8693-d2476875678a)

**Comment by tpillone** [comment]
Hi @Sam-Leistiko 
Thank you for reporting the error, I fixed it
Best

**Comment by Sam-Leistiko** [comment]
Hi Trestan,

Thank you so much for maintaining this database! I have found it very
useful, and I greatly appreciate your work in making this database free and
publicly available for all researchers.

Best,
Sam Leistiko

**Comment by tpillone** [comment]
Hi Sam, 
It's nice to know that ChlamDB is useful, thank you for your feedback!
Best,
Trestan
