### ISSUE TITLE
Comparison Tools Not Working

### ISSUE THREAD

**Issue by Sam-Leistiko** [metagenlab/chlamdb#34]
When I attempt to use the compare orthogroups tool, it keeps saying "Something went wrong!"
![image](https://github.com/metagenlab/chlamdb/assets/120612984/96983d39-ee72-4735-b9fb-11bb8d8ffe6b)

Additionally, when I try to use other comparison tools, I get this error message.
![image](https://github.com/metagenlab/chlamdb/assets/120612984/2a6001b9-652a-470c-b170-2cf741a9c18a)

**Comment by tpillone** [comment]
Sorry for this series of bugs, it's fixed!
